"""update exchange rates table rate_to_usd

Revision ID: 33d835814b75
Revises: 4436e536c8ef
Create Date: 2025-07-03 09:03:32.845509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d835814b75'
down_revision: Union[str, None] = '4436e536c8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rates', 'rate_to_usd',
               existing_type=sa.NUMERIC(precision=10, scale=10),
               type_=sa.Numeric(precision=10, scale=9),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rates', 'rate_to_usd',
               existing_type=sa.Numeric(precision=10, scale=9),
               type_=sa.NUMERIC(precision=10, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###
