"""update forecast_values to remove source_country column

Revision ID: 4445c5e03d09
Revises: 33d835814b75
Create Date: 2025-07-11 09:41:02.262557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4445c5e03d09'
down_revision: Union[str, None] = '33d835814b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_values', 'source_country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_values', sa.Column('source_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
