"""Add updated_by and updated_at

Revision ID: 880da22f56f0
Revises: 4445c5e03d09
Create Date: 2025-07-14 10:54:03.214387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880da22f56f0'
down_revision: Union[str, None] = '4445c5e03d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_values', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('forecast_values', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'forecast_values', 'users', ['updated_by'], ['id'])
    op.add_column('projects', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'updated_by')
    op.drop_constraint(None, 'forecast_values', type_='foreignkey')
    op.drop_column('forecast_values', 'updated_at')
    op.drop_column('forecast_values', 'updated_by')
    # ### end Alembic commands ###
