"""update exchange rates table

Revision ID: d41a2ba880b6
Revises: 03e55ae78ea8
Create Date: 2025-07-03 09:02:22.153973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41a2ba880b6'
down_revision: Union[str, None] = '03e55ae78ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rates', 'rate_to_usd',
               existing_type=sa.NUMERIC(precision=10, scale=12),
               type_=sa.Numeric(precision=10, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rates', 'rate_to_usd',
               existing_type=sa.Numeric(precision=10, scale=10),
               type_=sa.NUMERIC(precision=10, scale=12),
               existing_nullable=False)
    # ### end Alembic commands ###
